version: '3.8'

services:
  db:
    image: postgres:15
    container_name: petstore_postgres
    environment:
      POSTGRES_USER: petstore_user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: petstore_analytics
    volumes:
      # Том для сохранения данных БД между перезапусками контейнера
      - postgres_data:/var/lib/postgresql/data
      # Монтируем скрипты инициализации
      - ./init_db:/docker-entrypoint-initdb.d
      # Монтируем CSV файлы для доступа из скрипта импорта
      - ./data:/data_source
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: